# render.yaml
services:
  - type: web
    name: luna-shop
    env: docker
    autoDeploy: true
    plan: starter
    healthCheckPath: /
    envVars:
      - key: MYSQL_URL           # mysql://user:pass@host:port/db
        sync: false
      # O, si preferís individuales:
      # - { key: MYSQLHOST,     sync: false }
      # - { key: MYSQLPORT,     sync: false }
      # - { key: MYSQLDATABASE, sync: false }
      # - { key: MYSQLUSER,     sync: false }
      # - { key: MYSQLPASSWORD, sync: false }
    disks:
      - name: uploads
        mountPath: /var/www/html/public/uploads
        sizeGB: 2
