services:
  - type: web
    name: luna-tienda
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: STORE_NAME
        value: "LUNA — Tienda de Ropa"
      - key: CURRENCY
        value: "ARS"
      - key: TRANSFER_ALIAS
        value: "voleyppp"
      - key: BANK_INFO
        value: "Alias: voleyppp · Titular: LUNA"
